// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://klhvompynehlixcztwru.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtsaHZvbXB5bmVobGl4Y3p0d3J1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwOTg4MzUsImV4cCI6MjA2NjY3NDgzNX0.lQ2yRytsXZy3Yit34XonFq0JPhkEF86YqE0lkIpi4LI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);